version: '2.27'
services:
  db:
    container_name: pg_db
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=backend
      - POSTGRES_USER=backend
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
  bus_mapper:
    container_name: backend
    build: .
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env


volumes:
  db-data:

